- hosts: all
  tasks:
  - name: Clone dotfiles repository
    git: repo=https://github.com/tjeastman/dotfiles.git dest=~/projects/dotfiles
  - name: Clone emacs.d repository
    git: repo=https://github.com/tjeastman/emacs.d.git dest=~/projects/emacs.d
  - name: Link to emacs.d
    file: src=~/projects/emacs.d dest=~/.emacs.d state=link
  - name: Build Pymacs
    command: make chdir=~/.emacs.d/contrib/Pymacs creates=~/.emacs.d/contrib/Pymacs/pymacs.el
  - name: Link to zsh
    file: src=~/projects/dotfiles/zsh dest=~/.zsh state=link
  - name: Link to zshrc
    file: src=~/projects/dotfiles/zshrc dest=~/.zshrc state=link
  - name: Install rope
    pip: name=rope state=latest extra_args=--user
  - name: Install ropemode
    pip: name=ropemode state=latest extra_args=--user
  - name: Install ropemacs
    pip: name=ropemacs state=latest extra_args=--user
